// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Drizzle Kit configuration for LoopStorm Guard.
 *
 * Commands:
 *   bun run db:generate  — generate SQL migrations from schema changes
 *   bun run db:migrate   — apply pending migrations
 *   bun run db:studio    — open Drizzle Studio (visual DB browser)
 *
 * Migration output goes to ./drizzle/ directory:
 *   0001_create_tables.sql  — generated by drizzle-kit
 *   0002_enable_rls.sql     — hand-written RLS policies (DevOps gate required)
 */

import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    // DATABASE_URL must be set in the environment before running drizzle-kit
    url: process.env.DATABASE_URL ?? "",
  },
  // Verbose output for migration review
  verbose: true,
  strict: true,
});
